let playlist = [
  "Water Hands - Shot.mp3",
  "Water Hands - F that.mp3",
  "Water Hands - Sudden.mp3"
]

let mfdoom = [
  "All Caps.mp3",
  "America's Most Blunted.mp3",
  "Curls.mp3",
  "Doomsday.mp3",
  "Fancy Clown.mp3",
  "Figaro.mp3",
  "Kon Queso.mp3",
  "Meat Grinder.mp3",
  "Money Folder.mp3",
  "Next Levels.mp3",
  "One Beer.mp3",
  "Potholderz (feat. Count Bass D).mp3",
  "Raid.mp3",
  "Rainbows.mp3",
  "Rapp Snitch Knishes (feat. Mr. Fantastik).mp3",
  "Red and Gold.mp3",
  "Rhymes Like Dimes.mp3",
  "Go With the Flow.mp3"
]

let janplaylist = [
  '1979 (Official Music Video).mp3', 
  'A Different Age.mp3', 
  'A Heart Like Hers.mp3', 
  'Another One.mp3', 
  'Away.mp3', 
  'Bad Habit (Official Video).mp3', 
  'Be There.mp3', 
  'Blondie.mp3', 
  'Bubble Gum.mp3', 
  'Dark Red.mp3', 
  'Day Dreamin.mp3', 
  'F Song.mp3', 
  'For the First Time.mp3', 
  'Freaking Out the Neighborhood.mp3', 
  'Freaks.mp3', 
  'Friends.mp3', 
  'Go Easy.mp3', 
  'Heart To Heart.mp3', 
  'Home.mp3', 
  'Honey.mp3', 
  'In My Head.mp3', 
  'Inside Out.mp3',
  'Jealous.mp3', 
  'Kids.mp3', 
  'Money.mp3', 
  'Moonlight on the River.mp3', 
  'Mrs Magic.mp3', 
  'My Kind of Woman.mp3', 
  'Need 2.mp3', 
  'No Other Heart.mp3', 
  'Ode to Viceroy.mp3', 
  'On the Level.mp3', 
  'One More Love Song.mp3', 
  'Relax.mp3', 
  'Show Me How.mp3', 
  'Sparks.mp3', 
  'Steady.mp3', 
  'Still Beating.mp3', 
  'Swing Lynn.mp3', 
  'Telephones.mp3', 
  'Treat Her Better.mp3', 
  'Watching Him Fade Away.mp3', 
  'What Would I Do.mp3', 
  'Whered All the Time Go.mp3', 
  'YKWIM.mp3', 
  'Young.mp3',
  'HOME - Resonance.mp3'
]

let inesplaylist = [
  'All Alone.mp3', 
  "Attack on Titan - 'Call Your Name' with Lyrics.mp3", 
  'Attack on Titan FINAL BATTLE Soundtrack.mp3', 
  'Attack on Titan OST Bauklötze.mp3', 
  'Attack on Titan_ T-KT (ThanksAT) x ShingekiNoKyojin.mp3', 
  'Barricades.mp3', 
  'Be Quiet And Drive.mp3', 
  'Call of Silence.mp3', 
  'Whered All The Time Go.mp3', 
  'Feel Good.mp3', 
  'FETISH x Neuro Dimension - Bound.mp3', 
  'For the First Time.mp3', 
  'Greedy.mp3', 
  'I Cant Sleep.mp3', 
  'Inside Out.mp3', 
  'Me Gustas Tu.mp3', 
  'Memory Reboot (Slowed).mp3', 
  'My Kind of Woman.mp3', 
  'My Love Mine All Mine (Official Lyric Video).mp3', 
  'Reiner and Bertholdt reveal OST.mp3', 
  'Renegade.mp3', 
  'See you Later Eren.mp3', 
  'The Rumbling.mp3', 
  'Viva la Vida.mp3', 
  'Young.mp3',
  '2 Be Loved (Am I Ready).mp3',
  'Rutra - Vulture.mp3', 
  'Sure thing - Miguel (Wiskim Remix).mp3',
  'secret.mp3',
  'Another Love.mp3',
  'Hot girl bummer.mp3', 
  'Idfc (Tarro Remix).mp3', 
  'Starboy.mp3',
  'Bound.mp3', 
  'HOME - Resonance.mp3'
]

let inesrun = [
  'Hinkik - Momentum (Original Mix).mp3', 
  'Hung Up.mp3', 
  'Im Good (Blue).mp3', 
  'Memories.mp3', 
  'Miss You.mp3', 
  'Outside (Official Video).mp3', 
  'Summer.mp3',
  'secret.mp3'
]

let songs = [
  "1979 (Official Music Video).mp3",
  "2 Be Loved (Am I Ready).mp3",
  "A Different Age.mp3",
  "A Heart Like Hers.mp3",
  "All Alone.mp3",
  "All Caps.mp3",
  "America's Most Blunted.mp3",
  "Another One.mp3",
  "Attack on Titan - 'Call Your Name' with Lyrics.mp3",
  "Attack on Titan FINAL BATTLE Soundtrack.mp3",
  "Attack on Titan OST Bauklötze.mp3",
  "Attack on Titan_ T-KT (ThanksAT) x ShingekiNoKyojin.mp3",
  "Away.mp3",
  "Bad Habit (Official Video).mp3",
  "Barricades.mp3",
  "Be Quiet And Drive.mp3",
  "Be There.mp3",
  "Blondie.mp3",
  "Brasilian Skies.mp3",
  "Bring Me The Horizon - Can You Feel My Heart.mp3",
  "Bubble Gum.mp3",
  "Call of Silence.mp3",
  "Curls.mp3",
  "Dark Red.mp3",
  "Day Dreamin.mp3",
  "Doomsday.mp3",
  "F Song.mp3",
  "FETISH x Neuro Dimension - Bound.mp3",
  "Fancy Clown.mp3",
  "Feel Good.mp3",
  "Figaro.mp3",
  "For the First Time.mp3",
  "For the First Time.mp3",
  "Freaking Out the Neighborhood.mp3",
  "Freaks.mp3",
  "Friends.mp3",
  "Go With the Flow.mp3",
  "Go Easy.mp3",
  "Greedy.mp3",
  "Heart To Heart.mp3",
  "Hinkik - Momentum (Original Mix).mp3",
  "Home.mp3",
  "Honey.mp3",
  "Hung Up.mp3",
  "I Cant Sleep.mp3",
  "Im Good (Blue).mp3",
  "In My Head.mp3",
  "Inside Out.mp3",
  "Jealous.mp3",
  "Kids.mp3",
  "Kon Queso.mp3",
  "Letter Man ft. Suzu (Official Music Video).mp3",
  "Me Gustas Tu.mp3",
  "Meat Grinder.mp3",
  "Memories.mp3",
  "Memory Reboot (Slowed).mp3",
  "Miss You.mp3",
  "Money Folder.mp3",
  "Money.mp3",
  "Moonlight on the River.mp3",
  "Mrs Magic.mp3",
  "My Kind of Woman.mp3",
  "My Love Mine All Mine (Official Lyric Video).mp3",
  "Need 2.mp3",
  "Next Levels.mp3",
  "No Other Heart.mp3",
  "Ode to Viceroy.mp3",
  "On the Level.mp3",
  "One Beer.mp3",
  "One More Love Song.mp3",
  "Outside (Official Video).mp3",
  "Playaphonk - PHONKY TOWN (Audio).mp3",
  "Potholderz (feat. Count Bass D).mp3",
  "Raid.mp3",
  "Rainbows.mp3",
  "Rapp Snitch Knishes (feat. Mr. Fantastik).mp3",
  "Red and Gold.mp3",
  "Reiner and Bertholdt reveal OST.mp3",
  "Relax.mp3",
  "Renegade.mp3",
  "Rhymes Like Dimes.mp3",
  "Rutra - Vulture.mp3",
  "See you Later Eren.mp3",
  "Show Me How.mp3",
  "Sparks.mp3",
  "Steady.mp3",
  "Still Beating.mp3",
  "Summer.mp3",
  "Sure thing - Miguel (Wiskim Remix).mp3",
  "Swing Lynn.mp3",
  "Telephones.mp3",
  "The Rumbling.mp3",
  "Treat Her Better.mp3",
  "Viva la Vida.mp3",
  "Watching Him Fade Away.mp3",
  "Water Hands - F that.mp3",
  "Water Hands - Shot.mp3",
  "Water Hands - Sudden.mp3",
  "What Would I Do.mp3",
  "Whered All the Time Go.mp3",
  "YKWIM.mp3",
  "Young.mp3",
  'Another Love.mp3',
  'Hot girl bummer.mp3', 
  'Idfc (Tarro Remix).mp3', 
  'Starboy.mp3',
  'Bound.mp3', 
  'HOME - Resonance.mp3'
]

songs = songs.sort()
